### ISSUE TITLE
Inquiry regarding the pre-training process of the Safety Mapping Network in the "Learning Naturalistic Driving Environment" project.

### ISSUE THREAD

**Issue by CHAIJZ888** [michigan-traffic-lab/Learning-Naturalistic-Driving-Environment#1]
Dear Author,

I hope this message finds you well.

I am currently studying your work on the "Learning Naturalistic Driving Environment" project and have a specific inquiry about the safety_mapping_net.pt file used in the Safety Mapping Network.

I understand from the provided documentation and code that safety_mapping_net.pt is a pre-trained model. However, I could not find detailed information about its pre-training process. I am particularly interested in knowing:

Is there any specific script or code that was used to generate the safety_mapping_net.pt file?
Could you please provide some insights into how the safety_mapping_net.pt was pre-trained, including the dataset, training parameters, and optimization strategies used?
Any information you can provide on these questions would be extremely helpful for my research.

Thank you for your time and assistance.

Best regards

**Comment by yougeyxt** [comment]
Hi Jingzheng,

As we have discussed this through email, I will close this issue. Feel free to let me know if you have other questions.
