### ISSUE TITLE
Code-related questions about the scalability of the NeuralNDE framework in SUMO simulation

### ISSUE THREAD

**Issue by CHAIJZ888** [michigan-traffic-lab/Learning-Naturalistic-Driving-Environment#2]
Would it be possible for the author to share some example code or guide me to repositories that detail the implementation of NeuralNDE within SUMO for scenarios like intersections and roundabouts? If you could provide code on how to effectively integrate NeuralNDE with SUMO to manage specific traffic scenarios, as well as information on how to apply safety mapping rules to ensure safety, it would be greatly appreciated. Any guidance or resources you could offer would be immensely helpful. 

My email address is: chaijz@vip.qq.com

**Comment by yougeyxt** [comment]
Hi Jingzheng,

As we have discussed this through email, I will close this issue. Feel free to let me know if you have other questions.
